bash-my-aws/bash-my-aws

- bash_completion.sh
- test/generate_bash_completion
all other args use local filenames
> _bma_stacks_completion() only gets stack name for first arg

- doc/style.md
> Added start of style guide

- lib/instance-functions
- lib/stack-functions
> Scoped leaking variables

- README.md
- bash_completion.sh
- doc/developer-guide.md
- lib/stack-functions
similar to instance-tags. useful for auditing stacks.
> Add stack-tags function

- lib/asg-functions
- lib/instance-functions
- lib/stack-functions
> Change inline regex to be in variables

- lib/stack-functions
Output is sorted by `CreationTime`
Pipe output through `sort` to sort by StackName
New output fields:
- StackName
- StackStatus
- CreationTime
- LastUpdatedTime
> Append columns to output of stacks()

- lib/s3-functions
bucket-remove-force() deletes all objects from bucket first
> Add bucket-remove() bucket-remove-force()

- lib/vpc-functions
vpc-azs(): List AZs used for subnets in a VPC
vpc-az-count(): return number of different AZs used for subnets VPC
> Add vpc-azs() and vpc-az-count()

- lib/asg-functions
launch-configurations(): lists all Launch Configurations
asg-launch-configuration(): Lists Launch Configurations for ASG(s)
launch-configuration-asgs(): Lists ASG(s) for Launch Configuration(s)
> Add launch_configuration functions

- README.md
- update the web url to `bash-my-universe`
> Update web URL in README.md

- lib/cert-functions
- lib/elb-functions
certs() lists certs
certs-arn() is same as certs() but with added arn
cert-users() lists resource arns cert is InUseBy
cert-delete() does the dirty work for you
Also, some changes to elbs-functions we need for getting
info about cert users:
elbs() accepts Load Balancer names or ARNS
elb-stack() returns CloudFormation stack for elb
> cert-functions for Amazon Certificate Manager (ACM)

- test/stack-spec.sh
> s/main/Resolved arguments:/g

- lib/cloudtrail-functions
Returns current logging status
```
$ cloudtrail-status
USAGE: cloudtrail-status cloudtrail [cloudtrail]
```
```
$ cloudtrail-status Default
Default  IsLogging=true
```
> cloudtrail-status()

- lib/elb-functions
```
$ elbs
foo-loadBala-123456789012   2017-02-08T00:42:07.800Z
bar-loadBala-123456789012   2018-03-15T07:53:42.350Z
baz-Elb-123456789012        2018-05-30T07:17:21.320Z
```
> elbs() includes (and sorts on) CreatedTime

- lib/asg-functions
big refactor
- work with multiple asgs as input
- shellcheck
> Uplift asg functions

- lib/iam-functions
iam-functions: roles(), role-principal()
- roles() lists IAM Roles
- role-principal() shows AssumeRolePolicyDocument Principal
Now you can find broken trust with:
`roles | role-principal | grep AROA`
> iam-functions

- lib/rds-functions
rds-db-instances() returns list of database details
> Rds functions

- lib/log-functions
log-groups() lists CloudWatch log groups
> log-functions

- aliases
- lib/ecr-functions
ecr-repositories(): lists docker repositories in registry(s)
ecr-repository-images(): lists docker images in repository(s)
> ecr-functions

- lib/cert-functions
- lib/ecr-functions
- lib/elb-functions
- lib/iam-functions
- lib/instance-functions
- lib/lambda-functions
- lib/log-functions
- lib/rds-functions
- lib/region-functions
- lib/stack-functions
- lib/vpc-functions
- scripts/build
- test/function-names.sh
Force sorting to be byte-wise.
Otherwise, different systems may have different sort ordering.
> Ensure sort works the same for all users

- scripts/build
- scripts/build-completions
Removed the hard coded list of available completion 
it can be inferred from the files in the `scripts/completions`
> MInor clean up

- .gitignore
- cloudformation/docker-stack.yml
- cloudformation/params/docker-stack-params-skeleton.json
Cloudformation template that creates a simple ELB, ASG stack to run docker image.
For demonstration purposes only.
> Example CloudFormation template for docker-compose

- bin/bma
> /usr/bin/env bash

- aliases
- lib/asg-functions
- lib/aws-account-functions
- lib/cert-functions
- lib/cloudtrail-functions
- lib/ecr-functions
- lib/elb-functions
- lib/elbv2-functions
- lib/iam-functions
- lib/image-functions
- lib/instance-functions
- lib/keypair-functions
- lib/kms-functions
- lib/lambda-functions
- lib/region-functions
- lib/route53-functions
- lib/s3-functions
- lib/shared-functions
- lib/stack-functions
- lib/vpc-functions
This embeds the `pipe-skim` pattern in the function:
local foo=$(skim-stdin "$@")
First item from each line of STDIN will be appended to the arg list
> skim-stdin accepts args and appends to them

- docs/cloudformation-naming.md
- docs/command-reference.md
- docs/index.md
- docs/linuxconf2020.md
- docs/pipe-skimming.md
- mkdocs.yml
This should make search engine results more informative.
> Add titles and descriptions to doc pages

- aliases
- bash_completion.sh
- docs/command-reference.md
- functions
- lib/aws-account-functions
- scripts/build-completions
- scripts/completions/aws-account-completion
The account details produced can be piped into some of the other
aws-account functions or enjoyed on their own.
.
> aws-accounts() lists AWS Accounts in an Organization

- README.md
- docs/index.md
> Document 'bma' command completion

- aliases
- bash_completion.sh
- cloudformation/ssm.json
- docs/command-reference.md
- functions
- lib/instance-functions
- test/commands
Rather than going through ssh, I now use SSM sessions to connect to my instances.  bma didn't have this capability and it seemed simple enough, so I added it.  I'm not sure how the tests work but this didn't seem to break anything at least.  😄
> Add instance ssm
