- test/bash-spec.sh
- put a comment suggesting to use mktemp for temporary file names;
- reformatted the script to consistently follow the indentation;
- ensured that the variables are used consistently (no curly brackets unless they are truly required, double quotes around the variables, etc.)
- in the output() function ensured that if the $fails counter is not defined it would be also considered a failure;
- replaced multiple calls to echo with a single call to printf for performance;
- optimised some conditional logic to be fail-safe, e.g. set the failure state first, then conditionally update it if the test succeeds;
- in the to_have_mode() function relocated the negation check to the end of the routine, so it would be possible to do a negation check (I left the message re: 'file not found' intact).
> Reviewed the test framework and optimised it:

- lib/stack-functions
Currently prints out literal json string from response, eg: `"---\nAWSTemplateFormatVersion: 2010-09-09\nDescr...`
> Support YAML stack-template output

- lib/instance-functions
JMESPath backtick encloses a literal JSON expression.
Alternatively can escape this in bash eg: `join('\'' '\'',` which isn't as pretty
> Correct join separator

- lib/stack-functions
Check the stack size before attempting to pass template-body. Prevents error:
An error occurred (ValidationError) when calling the ValidateTemplate operation: 1 validation error detected: Value '
<magic>
' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
> Ensure stack template within size limits

- lib/stack-functions
This PR makes the following changes
* Adds an `--capabilities` option to `stack-create`, allowing the user to define what (if any) capabilities the stack is created with. No longer will it always use the excessive `CAPABILITY_NAMED_IAM`
* Adds an `--role-arn` option to allow the user to supply a CloudFormation Service Role
* Re-implements `stack-update` to detect the capabilities a stack was deployed with and act accordingly, no longer will it always use the excessive `CAPABILITY_NAMED_IAM`
* Minor formatting cleanup
* Addition of relevant error handling
I have tested it fairly extensively and the changes work and preserve all existing interfaces.
The specifics of how/why I implemented this change (and why, for example I didn't use `getopts` for my option parser) can be discussed if …
> Re-Implement Cloudformation Functions (more secure and additional features)

- lib/sts-functions
Clearly this was an oversight, update it to use the epoch time instead (a sensible default that is unlikely to have a collision).
> Any role assumed by sts-assume-role() will have the session-name hardcoded to 'mike'

- test/commands
- test/exercise-functions.sh
- test/function-names.sh
Overrides `aws` command to print command to STDOUT.
Runs *almost* all the functions.
> Exercise functions

- lib/stack-functions
After filtering out other resource types we can tidy up columns
by reducing whitespace
> Re-columnise stack-asgs

- lib/stack-functions
This change prepends stack_name to the output, in line with the functions for other resource types.
> stack-status() & stack-tags() accept >1 stack

- lib/stack-functions
Make destroying multiple stacks simpler.
You don't get an "Are you sure?" so be sure. 
``` 
$ stacks | grep barney
website-barney
audio-files-barney
$ stacks | grep barney | stack-delete
...
`
> stack-delete() accepts multiple stacks

- lib/stack-functions
stack-tag() returns the value of a named stack tag
stack-tag-apply() creates or updates a named stack-tag
stack-tag-delete() removes a stack-tag
** Warning **
Note that when updating stack tags, you need to specify all of the
ones you wish to exist. I believe they are managed stored within
the CloudFormation service, not the tagging service but this has
not been confirmed.
A known problem with making assumptions about tags based on the tags
returned by queries on resources like EC2 Instances is that if the
tagging service fails, you may get a list of instances but not their
tags. If this were the case with CloudFormation Stack Tags then the
stack-tag-apply() and stack-tag-delete() functions could remove
all tags in the case of a failure in tagging service.
I'll continue to attempt to …
> stack-tag() stack-tag-apply() stack-tag-delete()

- lib/vpc-functions
Subnet names are more likely to be visually scanned by user than
resource-id
> vpc-subnets() output sorted by name field

- lib/stack-functions
stack-diff() provides a nice familiar way to compare a local template with that of a stack.
Cloudformation changesets provide an alternative method but I find a diff of the template easier to read.
It's almost 2 years since AWS added support for YAML CloudFormation templates. bash-my-aws has supported YAML for most functions but defaulted to JSON. While JSON is still supported, we're now assuming templates are likely to be in yaml. On example is that the shortcuts for `stack-create` and `stack-update` now search for files ending in `'.json', '.yml', '.yaml'.
> YAML support for stack-diff() and other stack functions

- lib/stack-functions
Hi, very small addition to stack-recreate(), added in _stack_capabilities cos with out it the function failed when re-creating a stack with it
`An error occurred (InsufficientCapabilitiesException) when calling the CreateStack operation: Requires capabilities : [CAPABILITY_NAMED_IAM]`
Now the odds are high, that I've missed something so provide any feedback 😂
> Added --capabilities to stack-recreate()

- lib/instance-functions
I'm often interested in the instance I recently started.
The other alternative is instance name. If this is your preference,
pipe output through `sort -k 5` (and perhaps create an alias).
> Order instances() output by LaunchTime

- lib/asg-functions
- lib/cloudtrail-functions
- lib/elb-functions
- lib/instance-functions
- lib/s3-functions
- lib/shared-functions
- lib/stack-functions
- lib/vpc-functions
This is big and I'm very excited about it but it's a non breaking change.
I sat on it for a long time because I want to maintain interface
uniformity between functions. Last night I had a breakthrough while
walking the dogs.
Providing string(s) to grep for as args instead of piping through
the grep command offer two main benefits:
- less keystrokes: don't need to type `| grep`
- neater output:  it's run through `column` after filtering
I like short names. Sometimes people use long resource names which can
blow out the width of columns when listing them. If you keep the names
of your resources short then why should your view be tainted by the
verbose nomenclature of others? Now it needn't be.
**Before - looks terrible!**
```
$ stacks | grep web
example-ui-s3-website …
```
> List functions (like `stacks`) allow filtering.

- lib/instance-functions
Update function instance-terminate to accept instance-ids from STDIN.
This was disabled previously as I didn't know how to reattach a
terminal to read user input confirming they want to terminate the
listed instance(s).
This little baby is awesome:
```
[ -t 0 ] || exec </dev/tty # reattach keyboard to STDIN
```
Add functions:
- instance-termination-protection: shows termination protection status
- instance-termination-protection-disable: disable termination protection on instance(s)
- instance-termination-protection-enable: enable termination protection on instance(s)
> Change instance-terminate() behaviour

- lib/stack-functions
This change brings makes stack-tags() behave more like:
- stack-template()
- stack-parameters()
They provide a file that will be accepted as input to AWSCLI
when creating/updating stacks.
stack-tags-text() provides old behaviour of stack-tags()
- one line of text per stack with all tags (key=value)
Note that stack-tag() function may be more useful for checking
value of a specific tag:
```
$ stacks | stack-tag costcode
example-stack 1000
another-stack
yetmore-stack 1001
```
> Breaking change: stack-tags() returns JSON for single stack

- lib/stack-functions
It's due to comm expecting input to be sorted
> Warning from `comm` is an annoyance

- lib/image-functions
[For review - may still change]
Usage: images [owner] [image-id] [image-id]...
owner defaults to `self` or can one or more of:
- an AWS_ACCOUNT_ID  (e.g. 1234567890)
- an AWS_OWNER_ALIAS (amazon, amazon-marketplace, microsoft)
image_id can be one or more AMIs
example usage:
```
$ images
$ images 1234567890 | head -5
ami-11111111  2015-09-08T03:24:17.000Z  1234567890  example-app-3.123-1-ebs
ami-22222222  2015-09-08T06:27:17.000Z  1234567890  example-app-92
ami-33333333  2015-09-08T06:46:07.000Z  1234567890  example-app-93
ami-44444444  2015-09-08T07:18:27.000Z  1234567890  example-app-95
ami-55555555  2015-09-08T07:38:32.000Z  1234567890  example-app-96
```
> image-functions: images() lists AMIs

- lib/stack-functions
I don't want to be asked "are you sure" in response to:
```
$ stack-delete example-stack
```
but do when I use:
```
$ stacks mike | stack-terminate
```
I'd prefer to see the list of stacks that are to be deleted in
case I use a crummy search term.
> Only ask user to confirm deletion when input is piped

- .gitignore
- lib/stack-functions
- test/stack-spec.sh
I'm excited by this change! Solves #117 
Previously, providing params file when creating/updating a stack
meant you had to type out a long command like:
```shell
$ stack-create myapp-staging myapp.yml params/myapp-params-staging.json
```
Now, if your file and stack names follow the (completely optional!) BMA
convention you have the option of just doing this:
```shell
$ stack-create params/myapp-params-staging.json
```
It will generate the infer the stack and template file names from the
params file argument.
You **also have the option of providing just the stack or template name** as a single argument and the other values will be deduced based on the (completely optional) BMA naming convention. Another good reason to use it.
The existing argument options are still supported.
> stack-{create,update,diff} now accept single argument

- .travis.yml
- lib/stack-functions
- test/stack-spec.sh
Previously, this command displayed any values present.
Given `Description` and `ExportName` are optional, and
`Description` can have spaces it makes more sense to:
- omit `ExportName` (we have stack-exports() for that)
- put `Description` last (as it has spaces and may be long)
```
$ stack-outputs vpc-ratings-reviews-staging | grep Route
RouteTablePrivate1        rtb-XXXXXXXX     The routing table for private subnet 1
RouteTablePrivate2        rtb-XXXXXXXX     The routing table for private subnet 2
RouteTablePublic          rtb-XXXXXXXX     The routing table for public subnets
RouteTableRds             rtb-XXXXXXXX     The routing table for RDS subnets
RouteTableServices        rtb-XXXXXXXX     The routing table for services subnets
```
> Update output order of stack-outputs()

- .gitignore
- README.md
- generate_aliases.sh
- zsh_completion.sh
- create aliases for public functions in bash-my-functions
- invoke the functions using `~/.bash-my-aws/bin/bma`
- to invoke bash-my-aws functions as if they are bash scripts
- `./generate_aliases.sh` will generate a list of aliases
- `./zsh_completion.sh` to enable completion on zsh 
- update instructions in `README.md`
> Add support for zsh

- README.md
- bin/generate-aliases
- lib/misc-functions
- lib/region-functions
People calling functions via bin/bma better source region-functions
if they want region() to update AWS_DEFAULT_REGION in their shell.
> [WIP] Break out region-functions from misc-functions

- bin/generate-aliases
No reason to exclude them. It meant `asg-processes_suspended` was missing
> Generate aliases for all functions, including those with _

- lib/stack-functions
This allow you to view details for a set of stacks output
from another command.
```
$ vpcs | awk '{print $5}' | stacks
vpc-test   UPDATE_COMPLETE  2018-08-01T06:22:14.590Z  2019-06-01T11:28:01.119Z
vpc-test2  UPDATE_COMPLETE  2018-08-06T06:18:01.104Z  2019-06-01T11:28:26.516Z
```
> stacks() allows piping in of stack-names

- lib/log-functions
Turns out OSX version of `column` only supports short option names.
This change should make it work for OSX.
> Ensure we only use short option for column on OSX

- lib/stack-functions
> Certain stack operations, such as stack updates, should be initiated from the root stack rather than performed directly on nested stacks themselves.
[AWS - Working with Nested Stacks](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html)
> stacks() indicates whether stack is NESTED or NOT_NESTED

- bash_completion.sh
- scripts/completions/bma-completion
- scripts/completions/instance-completion
- Add type as a completion... 
+ when you type `bma t<tab>` will auto-complete to `bma type`
- Modify instances completion, so it works properly for zsh-users
> Improve completions

- lib/asg-functions
Breaking change!
Adds CreateTime as second-to-last column to output of `asgs` command.
The project rarely modifies output except to append columns to the end of a row.
This change was made for general consistency with where `CreatedTime` sits in other command output.
> asgs() includes CreatedTime (and orders by this column)

- docs/command-reference.md
- lib/instance-functions
Nice example of documentation driven development.
These were old commands and the output didn't look right in the new world.
> instance-{start,stop}: replace JSON output with lines

- cloudformation/ec2.yml
- docs/command-reference.md
- lib/instance-functions
Use line oriented output instead of JSON.
This function is old and benefited from some documentation driven development.
> instance-terminate: change from JSON to line output

- mkdocs.yml
I'm putting a lot of time into writing documentation and am really
curious how many people are benefiting from it.
I use Firefox web browser with tracking protection turned on and
believe it doesn't call out to Google Analytics (I did a quick test).
If you know of a free tracking tool that respects privacy then
please let me know.
> Add Google Analytics for https://bash-my-aws.org (explanation below)

- aliases
- cloudformation/docker-stack.yml
- docs/command-reference.md
- functions
- lib/asg-functions
- lib/aws-account-functions
- lib/cert-functions
- lib/cloudtrail-functions
- lib/ecr-functions
- lib/elb-functions
- lib/elbv2-functions
- lib/iam-functions
- lib/image-functions
- lib/instance-functions
- lib/keypair-functions
- lib/kms-functions
- lib/lambda-functions
- lib/log-functions
- lib/misc-functions
- lib/region-functions
- lib/route53-functions
- lib/s3-functions
- lib/shared-functions
- lib/stack-functions
- lib/vpc-functions
**Massive refactor - would appreciate if people try it out and report any problems**
Replace  `__bma_read_stdin` with `skimstdin` and reduce it to a one line function.
This forms part of a reference implementation of `pipe-skimming`, which involves commands
appending the first token from each line of STDIN to their argument list. Blog post to follow.
```shell
skimstdin() {
[[ -t 0 ]] || awk 'ORS=" " { print $1 }'
}
```
There's a bunch of other tidy up to bring older functions in line with more recent conventions in the project. It's some a motherload of a change and will need further review and testing.
> Simpler shared functions

- lib/lambda-functions
- lib/log-functions
Due to `column` command version in Ubuntu 18.04, that doesn't have the `--help` option, `lambda-functions` returns the followingo error:
After the error, lambda functions are listed.
To avoid this it is just a matter to send column errors to `/dev/null` when the test to determine $column_command is done. After the changes, `lambda-functions` works fine:
> Send column error message to dev-null due to "column" version in Ubuntu

- bin/bma
When running a command via `bin/bma` (the default when using aliases) we don't want bash to expand wildcards (globbing).
While it's unlikely that `*`s will be provided as arguments to `bin/bma` it's better to be safe than sorry.
> Prevent wildcard expansion in bin/bma

- lib/shared-functions
A one-liner using `echo` is much more readable *but* risks
problems from arguments with special characters (e.g. `-n`)
- Provide a format string to printf
- Remove need for subshell
- Make it (marginally?) more readable
> Refactor skim-stdin

- bin/bma
Added while testing breaking changes in aws-cli-v2
Also useful for testing with
[localstack](https://github.com/localstack/localstack)
e.g. `$ BMA_AWSCLI=awslocal stacks`
Also, print AWSCLI version when BMA_DEBUG=true
> Set $BMA_AWSCLI to specify which awscli to use

- lib/kms-functions
- lib/shared-functions
`kms-encrypt` will base64 encode input from STDIN (unless awscli version 1 is being used).
[aws-cli-v2 expects blobs to be base64 encoded](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam)
Part of #293
> aws-cli-v2 expects blobs to be base64 encoded

- lib/keypair-functions
EC2's `Get Windows Password` expects you to provide a key in
PEM format.
So instead of:
-----BEGIN OPENSSH PRIVATE KEY-----
you'll see:
-----BEGIN RSA PRIVATE KEY-----
> AWS was expecting a PEM format for `Get Windows Password`

- lib/instance-functions
Resolves #290 by copying the 'i-*' string detection from instance-ssh() to instance-ssh-details().
Help Text had already mentioned [login] so I assume that part can stay unchanged.
> Update instance-ssh-details to match instance-ssh

- lib/stack-functions
Fixes #302
[jq appends trailing newlines](https://github.com/stedolan/jq/issues/787)
> Removing trailing blank lines from stack-template output

- aliases
- bash_completion.sh
- docs/command-reference.md
- functions
- scripts/build
- scripts/build-completions
- scripts/completions/bma-completion
- test/check-completions
Update the build scripts.
Added the following text to each of the "generated" files: 
> \# DO NOT MANUALLY MODIFY THIS FILE.
> \# Use 'scripts/build' to regenerate if required.
i.e. `functions`, `aliases` and `bash_completion.sh`
Feel free to suggest better wordings.
Would be great if someone could also give this a test run ~
- Would serve as a good reminder that there is a build script.
PS. Seems like it fixed the documentation too for `instance-ssm` 😄
> Update build scripts

- lib/stack-functions
This is nice for stacks that are in a `DELETE_FAILED` status
```
✗ stack-resources snip
sg-snip                        AWS::EC2::SecurityGroup         DELETE_COMPLETE  snip
snip-development               AWS::EKS::Cluster               DELETE_FAILED    snip
sg-snip                        AWS::EC2::SecurityGroup         DELETE_FAILED    snip
IngressDefaultClusterToNodeSG  AWS::EC2::SecurityGroupIngress  DELETE_COMPLETE  snip
IngressInterNodeGroupSG        AWS::EC2::SecurityGroupIngress  DELETE_COMPLETE  snip
IngressNodeToDefaultClusterSG  AWS::EC2::SecurityGroupIngress  DELETE_COMPLETE  snip
```
> Add ResourceStatus to stack-resources

- aliases
- lib/region-functions
Shell doesn't pass environment variables to sub-processes unless they are exported.
```
$ A=1
$ bash -c 'echo $A'
$ export A  
$ bash -c 'echo $A'
1
```
Both `region` and `region-each` functions set `AWS_DEFAULT_REGION` variable, but they do not export it, hence they are not passed into `bma` sub-process and neither of those functions work as expected.
> Make sure that AWS_DEFAULT_REGION variable is exported

- bin/bma
AWS CLI version 2 provides the use of a client-side pager program for output.
By default, this feature returns all output through your operating system’s default pager program.
https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-clientside
> Disable AWS CLI version 2's client side pager.

- README.md
- lib/stack-functions
This PR updates the stack-diff function in a couple of simple ways.
* it corrects a problem on macOS where the `type` command doesn't have a "-p" flag.  Therefor the `stack-diff` function was always using plane `diff` even if `colordiff` was installed and available.
* it adds the ability to use the `icdiff` program, if available.  This has the affect of making the diff output colored and side-by-side.
* Finally, it adds more detail to the README to show the user it's possible to make the stack-diff output
more pretty.  I wasn't sure where to put this so you might want to reformat it to make it fit the rest of the documentation better.
> Make stack-diff output prettier

- bash_completion.sh
- scripts/build
- scripts/build-completions
Noticed changes to the default location. See https://github.com/bash-my-aws/bash-my-aws/pull/319
- `bash_completion.sh` is hardcoded to `"\${HOME}/.bash-my-aws"`
- If you re-run the build script, it will overwrite the `aliases` with resolved `project_root`. 
- Update the alias generation script to use `'\${BMA_HOME:-\$HOME/.bash-my-aws}` 
- Update the completion generation script to use `'\${BMA_HOME:-\$HOME/.bash-my-aws}` 
- Reran the build script to generate the `bash_completion.sh` and `aliases`
> Update build scripts to use $BMA_HOME

- lib/instance-functions
As per #324 , this PR proposes a tiny change to the handling of the ssh key path within the `instance_ssh()` function.
The change is literally from this:
```
-i "${BMA_SSH_DIR:-~/.ssh/}$keyname"
```
to this
```
-i "${BMA_SSH_DIR:-~/.ssh}/$keyname"
```
The rationale is that if `BMA_SSH_DIR` is missing a trailing slash, this will ensure that one is present. If `BMA_SSH_DIR` does have a trailing slash, then a non-fatal double-slash will be present (i.e. `/path/to/BMA_SSH_DIR//keyname`) and the connection will still work. Either way, the default behaviour of `~/.ssh/$keyname` remains intact.
With the current code, a `BMA_SSH_DIR` without a trailing slash results in e.g. `/path/to/BMA_SSH_DIRkeyname` which will obviously fail.
> Improve handling of ssh key path in instance_ssh()

- lib/stack-functions
https://www.gnu.org/software/grep/manual/grep.html
grep-3.8 introduces an obsolescence warning:
```
egrep: warning: egrep is obsolescent; using grep -E
```
> egrep is deprecated

- lib/elb-functions
Hi I had to do some ELB investigations in the last few days so I created these functions `elb-tag` and `elb-tags` to view ... wait for it ... elb tags.
They are direct copies of instance-tag and instance-tags. The only big difference is aws elb describe-tags doesn't support the --filter argument so going `elbs | elb-tag $tagname` would not filter out items without that tagname like I suspect instance-tag does. There might be a way to do similar filtering in jmespath if that's a deal-breaker, but I'm not too familiar with it.
Thought this might be helpful to share back. LMK what you think.
> Add elb tag reading functions

- README.md
- bin/bma
- docs/index.md
- test/exercise-functions.sh
Found a few reference to ~/.bash-my-aws which should instead use ${BMA_HOME:-$HOME/.bash-my-aws}
> Fixed a few references to standard path so BMA_HOME will work instead

- lib/instance-functions
Hi,
as per the discussion in #324 , I'd like to propose the following changes to `import-ssh()`:
* Declare all local variables on a single line.  This satisfies Shellcheck and reduces repeated `local x=y` visual clutter
* Switch the usage output to use `__bma_usage()`
* Rename `user` and `USERNAME` to `ssh_user`.  This varname is more descriptive, and by avoiding UPPERCASE, we avoid a potential collision in the environment "scope"
* Replace the multiple `echo | awk` sequences with a single `read -r` multiple variable assignment.  This is the main efficiency improvement provided by this PR.  This is, also, portable across the versions of `ksh`, `bash` and `zsh` that I've tested with.
I have increased the number of vars that use the optional brace syntax, but have not completely done so …
> Improve efficiency and consistency of instance-ssh()

- bash_completion.sh
- scripts/build-completions
This fixes tab completion when `BMA_HOME` is set. Corrects reference to https://github.com/bash-my-aws/bash-my-aws/blob/c85a77202fee8a41416f0ec455d48d8f64b677f9/bin/bma#L16
> scripts/build: correct path when BMA_HOME is set
